name: Build and Package IPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Debug Prints
        run: |
          ls /Applications/
          ls /
          ls
          ls /Users/runner

      - name: Build and archive app
        run: |
          ls
          mkdir -p build
          ls
          xcodebuild -scheme WidgetAnimation \
                     -project WidgetAnimation.xcodeproj \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/WidgetAnimation.xcarchive \
                     archive

      - name: Export IPA
        run: |
          cd build
          cd WidgetAnimation.xcarchive/Products/Applications
          mkdir Payload
          mv WidgetAnimation.app Payload/
          zip -r App.ipa Payload/
          mv App.ipa ../../..

      - name: Upload IPA to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ipa
          path: build/App.ipa
